name: Secrets and Environment Variables

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      WIN10_KEY: ${{secrets.WIN10_KEY}}

    steps:
      - name: Testing Echo
        run: echo "Hello!"
