name: Secrets and Environment Variables

on: workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      WIN10_KEY: ${{secrets.WIN10_KEY}}

    steps:
      - name: Testing Echo
        run: echo "Hello!"
