name: Secrets and Environment Variables

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Testing Echo
        env:
          WIN10_KEY: ${{secrets.WIN10_KEY}}
        run: echo "Hello!"
