name: Secrets and Environment Variables

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Testing Echo
        env:
          WIN10_KEY: ${{secrets.WIN10_KEY}}
        run: echo "Hello!"
